name: publish
concurrency:
  group: publish-${{ github.github.base_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
jobs:
  test-and-publish:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 8
          run_install: false
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get PNPM store directory
        id: pnpm-store
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/cache@v3
        name: Setup PNPM cache
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: 20
      - name: Run lint
        run: pnpm run ci:lint
      - name: Build Prisma Test DB
        run: pnpm exec prisma db push
      - name: Run tests
        run: pnpm run ci:test
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release

